version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: dev.dockerfile
    image: mindmakerdev
    volumes:
      - ./:/go/src/github.com/stanleynguyen/mindmaker
    networks:
      - mindmaker-net
    ports:
      - '8080:8080'

  redis:
    image: redis
    volumes:
      - ./tmp/redis/data/:/data
    networks:
      - mindmaker-net

  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - ./tmp/postgres/data:/var/lib/postgresql/data
  #   networks:
  #     - mindmaker-net

networks:
  mindmaker-net:
    driver: bridge
